name: Increment tag version

on:
  schedule:
    - cron: "*/6 * * * *"
    
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{github.token}}
          script: |
            const { owner, repo } = context.repo;
            const tags = await github.repos.listTags({
              owner,
              repo
            });
            const { data } = tags;
            const lastTagName = data.length > 0 ? data[0].name : "2.0.0";
            const semver = lastTagName.split('.');
            github.repos.createRelease({
              owner,
              repo,
              tag_name: `2.${Number(semver[1]) + 1}.0`,
            });



