name: Increment tag version

on:
  schedule:
    - cron: "*/5 * * * *"
    
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{github.token}}
          script: |
            const { owner, repo } = context.repo;
            const tags = await github.repos.listTags({
              owner,
              repo
            });
            const { data } = tags;
            const lastTagName = data.length > 0 ? data[data.length-1].name : "2.0.0";
            const semver = lastTagName.split('.');
            github.git.createRef({
              owner,
              repo,
              ref: `refs/tags/2.${semver[1] + 1)}.0`,
              sha: context.sha
            });



