name: Increment tag version

on:
  schedule:
    - cron: "*/10 * * * *"
    
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
      with:
        github-token: ${{github.token}}
        script: |
          console.log("test", Date.now())
          
