# This is a basic workflow that is manually triggered

name: Manual workflow
on:
  workflow_dispatch:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Create tag
      uses: actions/github-script@v3
      with:
        github-token: ${{github.token}}
        script: |
          const { owner, repo } = context.repo;
            const tags = await github.repos.listTags({
              owner,
              repo
            });
            const { data } = tags;
            console.log(data)
            const lastTagName = data.length > 0 ? data[0].name : "2.0.0";
            const semver = lastTagName.split('.');
            github.git.createRef({
              owner,
              repo,
              ref: `refs/tags/2.${Number(semver[1]) + 1}.0`,
              sha: context.sha
            });
