# This is a basic workflow that is manually triggered

name: Manual workflow
on:
  workflow_dispatch:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Create tag
      uses: actions/github-script@v3
      with:
        github-token: ${{github.token}}
        script: |
          const tags = await github.repos.listTags({
            owner: context.repo.owner,
            repo: context.repo.repo
          })
          const { data } = tags;
          const lastTagName = data.length > 0 ? data[data.length-1].name : "2.0.0";
          let semver = lastTagName.split('.');
          semver[1]++;
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${semver.join('.')}`,
            sha: context.sha
          });
