# This is a basic workflow that is manually triggered

name: Manual workflow
on:
  workflow_dispatch:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Create tag
      uses: actions/github-script@v3
      with:
        github-token: ${{github.token}}
        script: |
          console.log(github.repos.listTags({
            owner: context.repo.owner,
            repo: context.repo.repo
          }))
          /* github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/tagname",
            sha: context.sha
          }) */
