name: Two weeks manual workflow
on:
  workflow_dispatch:
jobs:
  two-weeks-release:
    runs-on: ubuntu-latest
    steps:
    - name: Create tag
      uses: actions/github-script@v3
      with:
        github-token: ${{github.token}}
        script: |
            Date.prototype.getWeekNumber = function () {
              var d = new Date(Date.UTC(this.getFullYear(), this.getMonth(), this.getDate()));
              var dayNum = d.getUTCDay() || 7;
              d.setUTCDate(d.getUTCDate() + 4 - dayNum);
              var yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
              return Math.ceil((((d - yearStart) / 86400000) + 1) / 7)
            };
            let newDate = new Date();
            if (newDate.getWeekNumber() % 2 === 0) {
              const { owner, repo } = context.repo;
              const tags = await github.repos.listTags({
                owner,
                repo
              });
              const { data } = tags;
              const lastTagName = data.length > 0 ? data[data.length-1].name;
              const semver = lastTagName.split('.');
              github.repos.createRelease({
                owner,
                repo,
                tag_name: `2.${Number(semver[1]) + 1}.0`,
              });
