name: Two weeks manual workflow
on:
  workflow_dispatch:
jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn add moment semver
      - name: Update tag
        uses: actions/github-script@v3
        with:
          github-token: ${{github.token}}
          script: |
            const semverInc = require(`${process.env.GITHUB_WORKSPACE}/node_modules/semver/functions/inc`)
            const moment = require(`${process.env.GITHUB_WORKSPACE}/node_modules/moment`)
            require(`${process.env.GITHUB_WORKSPACE}/node_modules/moment/locale/ro`)
            moment.locale('ro')
            const weekNumber = moment().week()
            if (weekNumber % 2 === 0) {
                const { owner, repo } = context.repo
                const { data } = await github.repos.listTags({
                    owner,
                    repo,
                })
                const { name } = data[0]
                github.repos.createRelease({
                    owner,
                    repo,
                    tag_name: `v${semverInc(name, 'minor')}`,
                })
            } else {
                console.log('No releases this week')
            }
