name: Two weeks manual workflow
on:
  workflow_dispatch:
jobs:
  two-weeks-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install moment
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{github.token}}
          script: |
            const moment = require(`${process.env.GITHUB_WORKSPACE}/node_modules/moment`)
            require(`${process.env.GITHUB_WORKSPACE}/node_modules/moment/locale/ro`);
            moment.locale('ro');
            const weekNumber = moment().week();
            if (weekNumber % 2 === 0) {
              const { owner, repo } = context.repo;
              const tags = await github.repos.listTags({
                owner,
                repo,
              });
              const { data } = tags;
              const lastTagName = data.length > 0 ? data[0].name : "2.0.0";
              const semver = lastTagName.split(".");
              github.repos.createRelease({
                owner,
                repo,
                tag_name: `2.${Number(semver[1]) + 1}.0`,
              });
            }
            else {
              console.log("No releases this week")
            }
