name: Two weeks manual workflow
on:
  workflow_dispatch:
jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn add moment@2.29.1 semver@7.3.5
      - name: Update tag
        uses: actions/github-script@v3
        with:
          github-token: ${{github.token}}
          script: |
            const semverInc = require(`${process.env.GITHUB_WORKSPACE}/node_modules/semver/functions/inc`)
            const moment = require(`${process.env.GITHUB_WORKSPACE}/node_modules/moment`)
            require(`${process.env.GITHUB_WORKSPACE}/node_modules/moment/locale/ro`)
            moment.locale('ro')
            const weekNumber = moment().week()
            if (weekNumber % 2 === 0) {
                const { owner, repo } = context.repo
                const latest = await github.repos.getLatestRelease({
                    owner,
                    repo,
                })
                console.log(latest)
                const { tag_name } = await github.repos.getLatestRelease({
                    owner,
                    repo,
                })
                const updatedTagName = `v${semverInc(tag_name, 'minor')}`
                github.repos.createRelease({
                    owner,
                    repo,
                    tag_name: updatedTagName,
                    name: updatedTagName
                })
            } else {
                console.log('No releases this week')
            }
